name: Terraform Plan & Apply

on:
  pull_request:
    paths:
      - 'envs/**'
      - 'modules/**'
  push:
    branches: [main]
    paths:
      - 'envs/**'
      - 'modules/**'

env:
  TF_VERSION: 1.8.0
  AWS_REGION: us-west-2

jobs:
  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run: { working-directory: envs/dev }
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: ${{ env.TF_VERSION }} }
      - run: terraform init -input=false
      - run: terraform plan -no-color
  apply:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run: { working-directory: envs/dev }
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: ${{ env.TF_VERSION }} }
      - run: terraform init -input=false
      - run: terraform apply -auto-approve

