version: '3.8'
services:
  grid-event-gateway:
    build: ./grid-event-gateway
    environment:
      IOT_ENDPOINT: ${IOT_ENDPOINT:-a1mgxpe8mg484j-ats.iot.us-west-2.amazonaws.com}
      MQTT_TOPIC_EVENTS: ${MQTT_TOPIC_EVENTS:-openadr/event}
      MQTT_TOPIC_RESPONSES: ${MQTT_TOPIC_RESPONSES:-openadr/response}
      MQTT_TOPIC_METERING: ${MQTT_TOPIC_METERING:-volttron/metering}
      CA_CERT: /certs/ca.crt
      CLIENT_CERT: /certs/client.crt
      PRIVATE_KEY: /certs/client.key
    volumes:
      - ./certs:/certs:ro
    ports:
      - "8080:8080"
      - "8081:8081"

  volttron-ven:
    build: ./volttron-ven
    environment:
      IOT_ENDPOINT: ${IOT_ENDPOINT:-a1mgxpe8mg484j-ats.iot.us-west-2.amazonaws.com}
      MQTT_TOPIC_EVENTS: ${MQTT_TOPIC_EVENTS:-openadr/event}
      MQTT_TOPIC_RESPONSES: ${MQTT_TOPIC_RESPONSES:-openadr/response}
      MQTT_TOPIC_METERING: ${MQTT_TOPIC_METERING:-volttron/metering}
      MQTT_TOPIC_STATUS: ${MQTT_TOPIC_STATUS:-volttron/dev}
      CA_CERT: /certs/ca.crt
      CLIENT_CERT: /certs/client.crt
      PRIVATE_KEY: /certs/client.key
    volumes:
      - ./certs:/certs:ro
    command: ["python", "ven_agent.py"]
    ports:
      - "8082:8080"
