"""init

Revision ID: c476bf48d7ac
Revises: 
Create Date: 2025-08-01 16:32:24.703464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c476bf48d7ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('ven_id', sa.String(), nullable=True),
    sa.Column('signal_name', sa.String(), nullable=True),
    sa.Column('signal_type', sa.String(), nullable=True),
    sa.Column('signal_payload', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('response_required', sa.String(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_ven_id'), ['ven_id'], unique=False)

    op.create_table('vens',
    sa.Column('ven_id', sa.String(), nullable=False),
    sa.Column('registration_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ven_id')
    )
    with op.batch_alter_table('vens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vens_registration_id'), ['registration_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_vens_ven_id'), ['ven_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vens_ven_id'))
        batch_op.drop_index(batch_op.f('ix_vens_registration_id'))

    op.drop_table('vens')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_ven_id'))
        batch_op.drop_index(batch_op.f('ix_events_event_id'))

    op.drop_table('events')
    # ### end Alembic commands ###
