name: Docker Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build openleadr image
        run: docker build -t openleadr ./openleadr
      - name: Build volttron image
        run: docker build -t volttron ./volttron
      - name: Build backend image
        run: docker build -t openadr-backend ./openadr_backend
