name: Lint and Test

on: [pull_request, push]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0
      
      - name: Terraform Format Check
        run: terraform fmt -recursive -check
      
      - name: Terraform Init (dev)
        run: terraform init -backend=false -input=false
        working-directory: envs/dev
      
      - name: Terraform Validate (dev)
        run: terraform validate
        working-directory: envs/dev

  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-testing.txt
      
      - name: Lint backend code
        run: |
          python -m flake8 ecs-backend/app/ --max-line-length=120 --extend-ignore=E203,W503
      
      - name: Run backend tests
        run: |
          cd ecs-backend && pytest --maxfail=5 -v --disable-warnings

  ven-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install VEN dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r volttron-ven/requirements.txt
          pip install pytest hypothesis
      
      - name: Run VEN tests
        run: |
          cd volttron-ven && pytest --maxfail=5 -v --disable-warnings

  gateway-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install Gateway dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r grid-event-gateway/requirements.txt
          pip install pytest
      
      - name: Run Gateway tests
        run: |
          cd grid-event-gateway && pytest --maxfail=5 -v --disable-warnings

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-testing.txt
      
      - name: Run integration tests
        run: |
          cd tests && pytest --maxfail=3 -v --disable-warnings