name: Terraform Lint & Format

on: [pull_request]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0
      # ── initialise the root so fmt/validate can find modules
      - name: Terraform init (root)
        run: terraform init -backend=false -input=false
      - run: terraform fmt -recursive -check

      # ── init the envs/dev workspace and then validate
      - name: Terraform init (envs/dev)
        run: terraform init -backend=false -input=false
        working-directory: envs/dev

      - run: terraform validate
        working-directory: envs/dev

      - name: Compile Python files
        run: python -m py_compile $(git ls-files '*.py')

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install paho aiosqlite fastapi uvicorn sqlalchemy asyncpg alembic python-dotenv pydantic pydantic-settings sqlmodel pytest httpx pytest_asyncio
      - name: Run openadr_backend tests
        run: pytest openadr_backend/tests
      - name: Run openleadr tests
        run: pytest openleadr/tests
      - name: Run volttron tests
        run: pytest volttron/tests
