name: Security Scan

on: [pull_request]

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Trivy
        uses: aquasecurity/trivy-action@v0.16.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          output: trivy.txt
      - uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy.txt
  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: python
      - uses: github/codeql-action/analyze@v3
