name: Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0
      - name: Install dependencies
        run: |
          pip install -r openleadr/requirements.txt -r volttron/requirements.txt \
            fastapi uvicorn sqlalchemy asyncpg alembic python-dotenv \
            pydantic pydantic-settings sqlmodel httpx pytest pytest-asyncio \
            aiosqlite paho-mqtt pyOpenSSL==22.1.0
      - name: Terraform checks
        run: ./scripts/check_terraform.sh
      - name: Run pytest
        env:
          PYTHONPATH: openadr_backend
        run: pytest
